tls:
  certificates:
    - keyFile: ./certs/_wildcard.local.dev-key.pem
      certFile: ./certs/_wildcard.local.dev.pem  
http:
  #middlewares:
    #rewriteHeaders:
      #plugin:
        #rewriteHeaders:
          #rewrites:
            #- header: "location"
              #regex: "^http://(.+)$"
              #replacement: "https://$1"
  routers:
    dashboard:
      entryPoints: 
        - "web"
      rule: "Host(`api.local.dev`)"
      service: "api@internal"

    api:
      entryPoints:
        - "websecure"
      rule: "Host(`api.local.dev`)"
      service: api
      tls: {}
    app:
      entryPoints:
        - "websecure"
      rule: "Host(`app.local.dev`)"
      service: app
      tls: {}
    keycloak:
      entryPoints:
        - "websecure"
      rule: "Host(`kc.local.dev`)"
      service: keycloak
      tls: {}
  services:
    api:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://localhost:9080"
    app:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://nginx"
    keycloak:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://keycloak:8080"
